version: '3.8'

services:
  jupyter:
    build: .
    container_name: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"  # Porta do Jupyter
    command: > 
      start-notebook.sh --NotebookApp.token=''
    networks:
      - spark-network
    volumes:
      - ./notebooks:/home/jovyan/work

networks:
  spark-network:
    driver: bridge